# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 210-ex4-julie-emma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300622210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4678360dff3940b994deceb555d37fa0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f4089cc4d4fe4a75ba5d9438df358c00 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4678360dff3940b994deceb555d37fa0 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '210-ex4-julie-emma'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d82e4d4acc448f28a1a9e10060f6bcb }}
        images: 'acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4678360dff3940b994deceb555d37fa0 }}/backend:${{ github.sha }}'